const projects = [
  {
    href: "repos#symantic-html",
    src: "./assets/horiseon2.png",
    alt: "SYMANTIC HTML",
    classes: "img-fluid html",
    id: 1,
  },
  {
    href: "repos#portfolio",
    src: "./assets/portfolio1.png",
    alt: "BEGINNER PORTFOLIO",
    classes: "img-fluid html css",
    id: 2,
  },
  {
    href: "repos#payroll",
    src: "./assets/employeetracker1.png",
    alt: "EMPLOYEE PAYROLL TRACKER",
    classes: "img-fluid html js",
    id: 3,
  },
  {
    href: "repos#personal-blog",
    src: "./assets/blog1-1.png",
    alt: "PERSONAL BLOG",
    classes: "img-fluid html css js",
    id: 4,
  },
  {
    href: "repos#taskboard",
    src: "./assets/taskboard1.png",
    alt: "TASKBOARD",
    classes: "img-fluid js bs jq html",
    id: 5,
  },
  {
    href: "repos#fitness",
    src: "./assets/fitness-tracker1.png",
    alt: "HEALTH AND FITNESS TRACKER",
    classes: "img-fluid html js tw",
    id: 6,
  },
  {
    href: "repos#weather",
    src: "./assets/weather-dashboard2.png",
    alt: "WEATHER DASHBOARD",
    classes: "img-fluid html js bs",
    id: 7,
  },
  {
    href: "repos#logo",
    src: "./assets/logo-generator1.png",
    alt: "LOGO GENERATOR",
    classes: "img-fluid js node",
    id: 8,
  },
  {
    href: "repos#readme",
    src: "./assets/readme-generator.png",
    alt: "README GENERATOR",
    classes: "img-fluid js node",
    id: 9,
  },
  {
    href: "repos#note-taker",
    src: "./assets/note-taker1.png",
    alt: "NOTE TAKER",
    classes: "img-fluid html css bs express js node",
    id: 10,
  },
  {
    href: "repos#employee",
    src: "./assets/employeedb.png",
    alt: "EMPLOYEE DATABASE",
    classes: "img-fluid js node insomnia express pg",
    id: 11,
  },
  {
    href: "repos#e-commerce",
    src: "./assets/e-commerce1.png",
    alt: "E-COMMERCE BACKEND",
    classes: "img-fluid js node insomnia express pg",
    id: 12,
  },
  {
    href: "repos#bootcamp",
    src: "./assets/bootcamp-banking1.png",
    alt: "BOOTCAMP BANKING",
    classes: "img-fluid css js jq bs insomnia node express pg hb html",
    id: 13,
  },
  {
    href: "repos#tech-blog",
    src: "./assets/blog2-1.png",
    alt: "TECH BLOG",
    classes: "img-fluid html css js jq bs insomnia node express pg hb",
    id: 14,
  },
  {
    href: "repos#social-network",
    src: "./assets/social-network1.png",
    alt: "SOCIAL NETWORK API",
    classes: "img-fluid js insomnia node mdb",
    id: 15,
  },
  {
    href: "repos.html#payroll-tracker",
    src: "./assets/placeholder.png",
    alt: "PROJECT IN PROGRESS",
    classes: "img-fluid",
    id: 16,
  },
  {
    href: "repos.html#payroll-tracker",
    src: "./assets/placeholder.png",
    alt: "PROJECT IN PROGRESS",
    classes: "img-fluid",
    id: 17,
  },
  {
    href: "repos.html#payroll-tracker",
    src: "./assets/placeholder.png",
    alt: "PROJECT IN PROGRESS",
    classes: "img-fluid",
    id: 18,
  },
  {
    href: "repos.html#payroll-tracker",
    src: "./assets/placeholder.png",
    alt: "PROJECT IN PROGRESS",
    classes: "img-fluid",
    id: 19,
  },
  {
    href: "repos.html#payroll-tracker",
    src: "./assets/placeholder.png",
    alt: "PROJECT IN PROGRESS",
    classes: "img-fluid",
    id: 20,
  },
  // Add more project objects here
];

const skills = [
  {
    href: "#",
    src: "./assets/html.png",
    alt: "HTML5",
    classes: "html",
  },
  {
    href: "#",
    src: "./assets/css.png",
    alt: "CSS3",
    classes: "css",
  },
  {
    href: "#",
    src: "./assets/javascript.png",
    alt: "JAVASCRIPT",
    classes: "js",
  },
  {
    href: "#",
    src: "./assets/bootstrap.png",
    alt: "BOOTSTRAP",
    classes: "bs",
  },
  {
    href: "#",
    src: "./assets/tailwind.png",
    alt: "TAILWIND",
    classes: "tw",
  },
  {
    href: "#",
    src: "./assets/jquery.png",
    alt: "JQUERY",
    classes: "jq",
  },
  {
    href: "#",
    src: "./assets/node.png",
    alt: "NODE.JS",
    classes: "node",
  },
  {
    href: "#",
    src: "./assets/express.png",
    alt: "EXPRESS.JS",
    classes: "node",
  },
  {
    href: "#",
    src: "./assets/postgresql.png",
    alt: "POSTGRESQL",
    classes: "pg",
  },
  {
    href: "#",
    src: "./assets/insomnia.png",
    alt: "INSOMNIA",
    classes: "insomnia",
  },
  {
    href: "#",
    src: "./assets/handlebars.png",
    alt: "HANDLEBARS",
    classes: "hb",
  },
  {
    href: "#",
    src: "./assets/mongodb.jpg",
    alt: "MONGODB",
    classes: "mdb",
  },
  {
    href: "#",
    src: "./assets/graphql.png",
    alt: "GAPHQL",
    classes: "gql",
  },
  {
    href: "#",
    src: "./assets/react.png",
    alt: "REACT.JS",
    classes: "react",
  },
  {
    href: "#",
    src: "./assets/redux.png",
    alt: "REDUX",
    classes: "redux",
  },
  // Add more skill objects here
];

export { projects, skills };
